dependencies: make crypto availability optional
Don't fail with import error if AES crypto isn't available, instead
only fail if the user actually tries to use it for NIP-04.
This allows use of aionostr for lightweight nostr stuff that doesn't
need NIP-04 without having to pull in an unused dependency.

```
Traceback (most recent call last):
  File "/tmp/tes/main.py", line 5, in <module>
    x.encrypt_message("test", "test")
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/user/code/electrum-aionostr-fork/src/electrum_aionostr/key.py", line 79, in encrypt_message
    raise CryptoBackendUnavailableError
electrum_aionostr.key.CryptoBackendUnavailableError: Error: at least one of ('pycryptodomex', 'cryptography') needs to be installed for NIP-04 functionality.
Install electrum-aionostr with with [crypto] feature: `pip install electrum-aionostr[crypto]`.
```